//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.06 at 11:08:47 AM PST 
//


package net.mikecarr.dives;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DiveDetails" type="{http://mikecarr.net/dives}DiveDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "diveDetails"
})
@XmlRootElement(name = "GetDiveDetailsResponse")
public class GetDiveDetailsResponse {

    @XmlElement(name = "DiveDetails", required = true)
    protected DiveDetails diveDetails;

    /**
     * Gets the value of the diveDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DiveDetails }
     *     
     */
    public DiveDetails getDiveDetails() {
        return diveDetails;
    }

    /**
     * Sets the value of the diveDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiveDetails }
     *     
     */
    public void setDiveDetails(DiveDetails value) {
        this.diveDetails = value;
    }

}
