//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.06 at 11:08:47 AM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mikecarr.net/dives", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.mikecarr.dives;
